# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrailMapper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrailMapper
  pod 'Alamofire', '~> 4.5'

  target 'TrailMapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrailMapperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
