# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrailMapper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrailMapper
  # For network access
  pod 'Alamofire', '~> 4.5'
  # for sqlite
  #pod 'FMDB'
  # For camera
  pod 'ALCameraViewController','~> 3.0.2'

    #For Creating models from JSON
    pod 'SwiftyJSON'

    #For key board related functions
    pod 'IQKeyboardManagerSwift'

  target 'TrailMapperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrailMapperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
